### PR TITLE
implement blinking microphone icon

### PR DESCRIPTION
**Pull request by n-maido**
Addresses issue #55 
 - Display a microphone icon when space is pressed or voice input is active
 - The microphone has a blinking green circle
 - Can be found in `ACE/src/chess/Microphone`
 
Gif:
(the gif is pixelated, but it doesn't look that way in the browser!)
microphone-screen-recording

cc @saum7800 @suhanichawla @atreyamaj

### CODE REVIEW

**Review by atreyamaj — APPROVED** [review]
Works perfectly for me! Awaiting reviews from @saum7800  @suhanichawla

**Comment by suhanichawla** [comment]
Mic looks really cool! :+1:
Just want to confirm if you have implemented interrupting speak positions as well

**Comment by n-maido** [comment]
Hello, I also pushed some commits that address issue #54 !
 - Allow user to interrupt the speak positions by pressing the escape button

https://user-images.githubusercontent.com/58193906/114968767-de94ad00-9e2b-11eb-92b7-4d40ab27135f.mp4

**Comment by n-maido** [comment]
> Mic looks really cool! 
> Just want to confirm if you have implemented interrupting speak positions as well

Yup!

**Comment by suhanichawla** [comment]
Awesome, working perfectly! :star:

**Review by suhanichawla — APPROVED** [review]

**Pull request merged**
